[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
